# Generated by Django 3.2.12 on 2022-03-19 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=200, verbose_name='Nome da receita')),
                ('ingredientes', models.TextField(verbose_name='Ingredientes')),
                ('modo_preparo', models.TextField(verbose_name='Modo de preparo')),
                ('tempo_preparo', models.IntegerField(verbose_name='Tempo de preparo')),
                ('rendimento', models.TextField(max_length=100, verbose_name='Rendimento')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('date_receita', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
